"""add_currency_to_budget

Revision ID: 1bf23ef769e2
Revises: 97af3d8f5d33
Create Date: 2026-03-03 08:46:41.359383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf23ef769e2'
down_revision = '97af3d8f5d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='GBP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
