"""add currency to transaction

Revision ID: 97af3d8f5d33
Revises: 
Create Date: 2026-03-03 08:24:28.586910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97af3d8f5d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='GBP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
