name: Automate action

on:
  push:
    branches:
      - main
      - develop


jobs:
  pytests:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v5
        
      - name: install python
        uses:  actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.9"
          enable-cache: true
        
      - name: install dependencies
        run: uv sync --locked --all-extras --dev

      - name: run tests
        run: uv run pytest tests

  docker-build:
    runs-on: ubuntu-latest
    needs: pytests

    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: clone
        uses: actions/checkout@v5
      
      - name: login github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: push docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}


